package main

import (
	"log"
	"os"

	_ "github.com/Fajarriswandi/dms-app/backend/docs" // docs is generated by Swag CLI
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/requestid"
	"github.com/gofiber/swagger"
)

// @title           Pedeve App Backend API
// @version         1.0
// @description     Pedeve App Backend API
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api/v1

// @securityDefinitions.apikey  BearerAuth
// @in                          header
// @name                        Authorization
// @description                 Type "Bearer" followed by a space and JWT token. Atau menggunakan httpOnly cookie (auth_token) untuk keamanan yang lebih baik.

// @note                        Catatan Teknis API:
// @note                        1. Framework: Menggunakan Fiber v2 dengan performa tinggi (fasthttp)
// @note                        2. Authentication: JWT token dengan httpOnly cookie untuk mencegah XSS attacks
// @note                        3. Rate Limiting:
// @note                           - General API: 100 requests/second, burst: 50
// @note                           - Auth endpoints: 5 requests/minute, burst: 5 (untuk prevent brute force)
// @note                        4. Security Headers: X-Content-Type-Options, X-XSS-Protection, CSP, HSTS
// @note                        5. CSRF Protection: Double-submit cookie pattern untuk state-changing requests (POST, PUT, DELETE, PATCH)
// @note                        6. Audit Logging: Semua aksi user dan error teknis dicatat dalam audit log
// @note                        7. 2FA Support: TOTP-based 2FA dengan backup codes untuk recovery
// @note                        8. Error Handling: Centralized error logging dengan stack trace untuk debugging
// @note                        9. Database: PostgreSQL/SQLite dengan GORM ORM, auto-migration enabled
// @note                        10. CORS: Configured untuk localhost:5173 (Vite dev) dan localhost:3000
func main() {
	// Inisialisasi database
	InitDB()

	// Inisialisasi audit logger
	InitAuditLogger()

	// Mulai cleanup token CSRF
	StartCSRFTokenCleanup()

	// Mulai cleanup audit logs (retention policy)
	StartAuditLogCleanup()

	// Seed user superadmin
	SeedSuperAdmin()

	// Setup Fiber app
	app := fiber.New(fiber.Config{
		ErrorHandler: func(c *fiber.Ctx, err error) error {
			// Custom error handler untuk logging error ke audit log
			code := fiber.StatusInternalServerError
			if e, ok := err.(*fiber.Error); ok {
				code = e.Code
			}

			// Log error ke audit log
			details := map[string]interface{}{
				"status_code": code,
				"error":       err.Error(),
			}
			LogTechnicalError(err, c, details)

			return c.Status(code).JSON(ErrorResponse{
				Error:   "internal_error",
				Message: err.Error(),
			})
		},
	})

	// Middleware global
	app.Use(RecoverMiddleware)                       // Custom recover middleware dengan error logging (harus di awal)
	app.Use(logger.New())                            // Logger middleware
	app.Use(requestid.New())                         // Request ID middleware
	app.Use(SecurityHeadersMiddleware)               // Header keamanan
	app.Use(ErrorHandlerMiddleware)                  // Log error teknis ke audit log
	app.Use(RateLimitMiddleware(generalRateLimiter)) // Rate limiting umum

	// CORS dengan peningkatan keamanan
	app.Use(cors.New(cors.Config{
		AllowOrigins:     "http://localhost:5173,http://localhost:3000",
		AllowMethods:     "GET,POST,PUT,DELETE,OPTIONS,PATCH",
		AllowHeaders:     "Accept,Authorization,Content-Type,X-CSRF-Token,X-Requested-With",
		ExposeHeaders:    "Link,X-Total-Count",
		AllowCredentials: true,
		MaxAge:           300,
	}))

	// Routes
	app.Get("/", indexHandler)
	app.Get("/health", healthHandler)

	// API v1
	api := app.Group("/api/v1")
	api.Get("/", apiInfoHandler)

	// Endpoint token CSRF (public, tidak perlu auth)
	api.Get("/csrf-token", GetCSRFTokenHandler)

	// Route autentikasi (public) - dengan rate limiting
	// Catatan Teknis:
	// - Endpoint register dihapus karena akan dihandle oleh modul management user
	// - Rate limiting khusus untuk auth endpoints (5 req/min, burst: 5) untuk prevent brute force
	// - Login endpoint mendukung 2FA, jika user memiliki 2FA aktif, akan return requires_2fa: true
	authPublic := api.Group("/auth", AuthRateLimitMiddleware)
	authPublic.Post("/login", Login)

	// Route yang dilindungi (memerlukan JWT)
	// Catatan Teknis:
	// - Semua endpoint di bawah ini memerlukan JWT token valid (dalam cookie atau Authorization header)
	// - CSRF protection diterapkan untuk state-changing methods (POST, PUT, DELETE, PATCH)
	// - GET methods tidak memerlukan CSRF token karena read-only
	protected := api.Group("", JWTAuthMiddleware, CSRFMiddleware)

	// Endpoint profil dan logout user
	protected.Get("/auth/profile", GetProfile)
	protected.Post("/auth/logout", Logout)

	// Route 2FA (Two-Factor Authentication)
	// Catatan: Semua endpoint 2FA memerlukan user sudah login terlebih dahulu
	protected.Post("/auth/2fa/generate", Generate2FASecret) // Generate secret dan QR code
	protected.Post("/auth/2fa/verify", Verify2FA)           // Verifikasi kode dan aktifkan 2FA
	protected.Post("/auth/2fa/disable", Disable2FA)         // Nonaktifkan 2FA (membutuhkan CSRF token)
	protected.Get("/auth/2fa/status", Get2FAStatus)         // Cek status 2FA user

	// Route audit logs (untuk monitoring dan audit trail)
	// Catatan: Admin/superadmin dapat melihat semua logs, user reguler hanya melihat logs sendiri
	protected.Get("/audit-logs", GetAuditLogsHandler)           // List audit logs dengan pagination dan filter
	protected.Get("/audit-logs/stats", GetAuditLogStatsHandler) // Statistik audit logs (total, breakdown, retention policy)

	// Route documents (dilindungi)
	// Catatan: Semua CRUD operations untuk documents memerlukan authentication dan CSRF token
	protected.Get("/documents", getDocumentsHandler)          // List semua documents
	protected.Get("/documents/:id", getDocumentHandler)       // Detail document by ID
	protected.Post("/documents", createDocumentHandler)       // Create document baru (memerlukan CSRF)
	protected.Put("/documents/:id", updateDocumentHandler)    // Update document (memerlukan CSRF)
	protected.Delete("/documents/:id", deleteDocumentHandler) // Delete document (memerlukan CSRF)

	// Swagger
	app.Get("/swagger/*", swagger.HandlerDefault)

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Server starting on port :%s", port)
	log.Printf("Swagger UI available at http://localhost:%s/swagger/index.html", port)
	log.Printf("API Base URL: http://localhost:%s/api/v1", port)

	if err := app.Listen(":" + port); err != nil {
		log.Fatal(err)
	}
}

// indexHandler handles the root endpoint (untuk Fiber)
// @Summary      Root endpoint
// @Description  Returns API information
// @Tags         General
// @Accept       json
// @Produce      json
// @Success      200  {object}  map[string]string
// @Router       / [get]
func indexHandler(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{
		"message": "Pedeve App Backend API",
		"version": "1.0.0",
		"swagger": "/swagger/index.html",
	})
}

// healthHandler handles health check (untuk Fiber)
// @Summary      Health check
// @Description  Returns health status
// @Tags         General
// @Accept       json
// @Produce      json
// @Success      200  {object}  map[string]string
// @Router       /health [get]
func healthHandler(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{
		"status":  "OK",
		"service": "pedeve-backend",
	})
}

// apiInfoHandler returns API information (untuk Fiber)
// @Summary      API Information
// @Description  Returns API version and endpoints
// @Tags         General
// @Accept       json
// @Produce      json
// @Success      200  {object}  map[string]interface{}
// @Router       /api/v1 [get]
func apiInfoHandler(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{
		"api":     "Pedeve App Backend API",
		"version": "1.0.0",
		"endpoints": fiber.Map{
			"documents": "/api/v1/documents",
			"swagger":   "/swagger/index.html",
		},
	})
}

// Document merepresentasikan sebuah document
type Document struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Content     string `json:"content"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

// getDocumentsHandler returns list of documents (untuk Fiber)
// @Summary      Get all documents
// @Description  Returns a list of all documents (requires authentication)
// @Tags         Documents
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Success      200  {array}   Document
// @Failure      401  {object}  ErrorResponse
// @Router       /api/v1/documents [get]
func getDocumentsHandler(c *fiber.Ctx) error {
	documents := []Document{
		{
			ID:          "1",
			Title:       "Sample Document 1",
			Description: "This is a sample document",
			Content:     "Document content here...",
			CreatedAt:   "2024-01-01T00:00:00Z",
			UpdatedAt:   "2024-01-01T00:00:00Z",
		},
		{
			ID:          "2",
			Title:       "Sample Document 2",
			Description: "Another sample document",
			Content:     "More document content...",
			CreatedAt:   "2024-01-02T00:00:00Z",
			UpdatedAt:   "2024-01-02T00:00:00Z",
		},
	}
	return c.JSON(documents)
}

// getDocumentHandler returns a single document (untuk Fiber)
// @Summary      Get document by ID
// @Description  Returns a single document by ID (requires authentication)
// @Tags         Documents
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        id   path      string  true  "Document ID"
// @Success      200  {object}  Document
// @Failure      401  {object}  ErrorResponse
// @Failure      404  {object}  ErrorResponse
// @Router       /api/v1/documents/{id} [get]
func getDocumentHandler(c *fiber.Ctx) error {
	id := c.Params("id")
	document := Document{
		ID:          id,
		Title:       "Sample Document",
		Description: "This is a sample document",
		Content:     "Document content here...",
		CreatedAt:   "2024-01-01T00:00:00Z",
		UpdatedAt:   "2024-01-01T00:00:00Z",
	}
	return c.JSON(document)
}

// createDocumentHandler creates a new document (untuk Fiber)
// @Summary      Create document
// @Description  Creates a new document (requires authentication)
// @Tags         Documents
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        document  body      Document  true  "Document object"
// @Success      201       {object}  Document
// @Failure      400       {object}  ErrorResponse
// @Failure      401       {object}  ErrorResponse
// @Router       /api/v1/documents [post]
func createDocumentHandler(c *fiber.Ctx) error {
	document := Document{
		ID:          "3",
		Title:       "New Document",
		Description: "A newly created document",
		Content:     "New document content...",
		CreatedAt:   "2024-01-03T00:00:00Z",
		UpdatedAt:   "2024-01-03T00:00:00Z",
	}
	return c.Status(fiber.StatusCreated).JSON(document)
}

// updateDocumentHandler updates a document (untuk Fiber)
// @Summary      Update document
// @Description  Updates an existing document (requires authentication)
// @Tags         Documents
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        id        path      string    true  "Document ID"
// @Param        document  body      Document  true  "Document object"
// @Success      200       {object}  Document
// @Failure      401       {object}  ErrorResponse
// @Failure      404       {object}  ErrorResponse
// @Router       /api/v1/documents/{id} [put]
func updateDocumentHandler(c *fiber.Ctx) error {
	id := c.Params("id")
	document := Document{
		ID:          id,
		Title:       "Updated Document",
		Description: "This document has been updated",
		Content:     "Updated content...",
		CreatedAt:   "2024-01-01T00:00:00Z",
		UpdatedAt:   "2024-01-03T00:00:00Z",
	}
	return c.JSON(document)
}

// deleteDocumentHandler deletes a document (untuk Fiber)
// @Summary      Delete document
// @Description  Deletes a document by ID (requires authentication)
// @Tags         Documents
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        id   path      string  true  "Document ID"
// @Success      200  {object}  map[string]string
// @Failure      401  {object}  ErrorResponse
// @Failure      404  {object}  ErrorResponse
// @Router       /api/v1/documents/{id} [delete]
func deleteDocumentHandler(c *fiber.Ctx) error {
	id := c.Params("id")
	return c.JSON(fiber.Map{
		"message": "Document " + id + " deleted successfully",
	})
}
