package main

import (
	"os"

	_ "github.com/Fajarriswandi/dms-app/backend/docs" // docs is generated by Swag CLI
	"github.com/Fajarriswandi/dms-app/backend/internal/delivery/http"
	"github.com/Fajarriswandi/dms-app/backend/internal/infrastructure/audit"
	"github.com/Fajarriswandi/dms-app/backend/internal/infrastructure/database"
	"github.com/Fajarriswandi/dms-app/backend/internal/infrastructure/logger"
	"github.com/Fajarriswandi/dms-app/backend/internal/infrastructure/seed"
	"github.com/Fajarriswandi/dms-app/backend/internal/middleware"
	"github.com/Fajarriswandi/dms-app/backend/internal/usecase"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/requestid"
	"github.com/gofiber/swagger"
	"go.uber.org/zap"
)

// @title           Pedeve App Backend API
// @version         1.0
// @description     Pedeve App Backend API dengan struktur Clean Architecture
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api/v1

// @securityDefinitions.apikey  BearerAuth
// @in                          header
// @name                        Authorization
// @description                 Type "Bearer" followed by a space and JWT token. Atau menggunakan httpOnly cookie (auth_token) untuk keamanan yang lebih baik.

// @note                        Catatan Teknis API:
// @note                        1. Framework: Menggunakan Fiber v2 dengan performa tinggi (fasthttp)
// @note                        2. Architecture: Clean Architecture dengan struktur cmd/, internal/
// @note                        3. Authentication: JWT token dengan httpOnly cookie untuk mencegah XSS attacks
// @note                        4. Rate Limiting: General API (100 req/s, burst: 50), Auth endpoints (5 req/min, burst: 5)
// @note                        5. Security Headers: X-Content-Type-Options, X-XSS-Protection, CSP, HSTS
// @note                        6. CSRF Protection: Double-submit cookie pattern untuk state-changing requests
// @note                        7. Audit Logging: Semua aksi user dan error teknis dicatat dalam audit log
// @note                        8. 2FA Support: TOTP-based 2FA dengan backup codes untuk recovery
// @note                        9. Error Handling: Centralized error logging dengan stack trace untuk debugging
// @note                        10. Database: PostgreSQL/SQLite dengan GORM ORM, auto-migration enabled
// @note                        11. CORS: Configured untuk localhost:5173 (Vite dev) dan localhost:3000
func main() {
	// Inisialisasi zap logger
	logger.InitLogger()
	defer logger.Sync()
	zapLog := logger.GetLogger()

	// Inisialisasi database
	database.InitDB()

	// Inisialisasi audit logger
	audit.InitAuditLogger()

	// Mulai cleanup token CSRF
	middleware.StartCSRFTokenCleanup()

	// Mulai cleanup audit logs (retention policy)
	usecase.StartAuditLogCleanup()

	// Seed user superadmin
	seed.SeedSuperAdmin()

	// Setup Fiber app
	app := fiber.New(fiber.Config{
		ErrorHandler: func(c *fiber.Ctx, err error) error {
			// Custom error handler untuk logging error ke audit log
			code := fiber.StatusInternalServerError
			if e, ok := err.(*fiber.Error); ok {
				code = e.Code
			}

			// Log error ke audit log
			details := map[string]interface{}{
				"status_code": code,
				"error":       err.Error(),
			}
			middleware.LogTechnicalError(err, c, details)

			return c.Status(code).JSON(fiber.Map{
				"error":   "internal_error",
				"message": err.Error(),
			})
		},
	})

	// Middleware global
	app.Use(middleware.RecoverMiddleware)                                  // Custom recover middleware dengan error logging (harus di awal)
	app.Use(middleware.ZapLoggerMiddleware(zapLog))                        // Zap logger middleware untuk HTTP requests
	app.Use(requestid.New())                                               // Request ID middleware
	app.Use(middleware.SecurityHeadersMiddleware)                          // Header keamanan
	app.Use(middleware.ErrorHandlerMiddleware)                             // Log error teknis ke audit log
	
	// Rate limiting: hanya aktif di production
	// Di development (ENV != "production"), rate limiting otomatis di-bypass di middleware (lihat rate_limit.go)
	// Atau bisa disable sepenuhnya dengan DISABLE_RATE_LIMIT=true
	env := os.Getenv("ENV")
	disableRateLimit := os.Getenv("DISABLE_RATE_LIMIT") == "true"
	
	if disableRateLimit {
		zapLog.Info("Rate limiting completely disabled (DISABLE_RATE_LIMIT=true)")
	} else if env != "production" {
		zapLog.Info("Rate limiting will be bypassed in development mode",
			zap.String("env", env),
		)
		// Tetap tambahkan middleware, tapi akan di-bypass di dalamnya
		app.Use(middleware.RateLimitMiddleware(middleware.GeneralRateLimiter))
	} else {
		// Production: aktifkan rate limiting
		app.Use(middleware.RateLimitMiddleware(middleware.GeneralRateLimiter))
	}

	// CORS dengan peningkatan keamanan
	app.Use(cors.New(cors.Config{
		AllowOrigins:     "http://localhost:5173,http://localhost:3000",
		AllowMethods:     "GET,POST,PUT,DELETE,OPTIONS,PATCH",
		AllowHeaders:     "Accept,Authorization,Content-Type,X-CSRF-Token,X-Requested-With",
		ExposeHeaders:    "Link,X-Total-Count",
		AllowCredentials: true,
		MaxAge:           300,
	}))

	// Routes
	app.Get("/", indexHandler)
	app.Get("/health", healthHandler)

	// API v1
	api := app.Group("/api/v1")
	api.Get("/", apiInfoHandler)

	// Endpoint token CSRF (public, tidak perlu auth)
	api.Get("/csrf-token", http.GetCSRFTokenHandler)

	// Route autentikasi (public) - dengan rate limiting (bypass di development)
	// AuthRateLimitMiddleware akan otomatis bypass di development (lihat rate_limit.go)
	authPublic := api.Group("/auth", middleware.AuthRateLimitMiddleware)
	authPublic.Post("/login", http.Login)

	// Route yang dilindungi (memerlukan JWT)
	protected := api.Group("", middleware.JWTAuthMiddleware, middleware.CSRFMiddleware)

	// Endpoint profil dan logout user
	protected.Get("/auth/profile", http.GetProfile)
	protected.Post("/auth/logout", http.Logout)

	// Route 2FA (Two-Factor Authentication)
	protected.Post("/auth/2fa/generate", http.Generate2FASecret)
	protected.Post("/auth/2fa/verify", http.Verify2FA)
	protected.Post("/auth/2fa/disable", http.Disable2FA)
	protected.Get("/auth/2fa/status", http.Get2FAStatus)

	// Route audit logs
	protected.Get("/audit-logs", http.GetAuditLogsHandler)
	protected.Get("/audit-logs/stats", http.GetAuditLogStatsHandler)

	// Route documents (dilindungi)
	protected.Get("/documents", http.GetDocumentsHandler)
	protected.Get("/documents/:id", http.GetDocumentHandler)
	protected.Post("/documents", http.CreateDocumentHandler)
	protected.Put("/documents/:id", http.UpdateDocumentHandler)
	protected.Delete("/documents/:id", http.DeleteDocumentHandler)

	// Swagger documentation
	app.Get("/swagger/*", swagger.HandlerDefault)

	// Start server
	port := ":8080"
	zapLog.Info("Server starting",
		zap.String("port", port),
		zap.String("swagger", "http://localhost"+port+"/swagger/index.html"),
	)
	if err := app.Listen(port); err != nil {
		zapLog.Fatal("Failed to start server", zap.Error(err))
	}
}

// indexHandler returns basic API information
func indexHandler(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{
		"message": "Pedeve App Backend API",
		"version": "1.0.0",
		"docs":    "/swagger/index.html",
	})
}

// healthHandler returns health status
// @Summary      Health check
// @Description  Returns API health status
// @Tags         General
// @Accept       json
// @Produce      json
// @Success      200  {object}  map[string]string
// @Router       /health [get]
func healthHandler(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{
		"status":  "OK",
		"service": "pedeve-backend",
	})
}

// apiInfoHandler returns API information
// @Summary      API Information
// @Description  Returns API version and endpoints
// @Tags         General
// @Accept       json
// @Produce      json
// @Success      200  {object}  map[string]interface{}
// @Router       /api/v1 [get]
func apiInfoHandler(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{
		"api":     "Pedeve App Backend API",
		"version": "1.0.0",
		"endpoints": fiber.Map{
			"documents": "/api/v1/documents",
			"swagger":   "/swagger/index.html",
		},
	})
}

