package main

import (
	"os"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/requestid"
	"github.com/gofiber/swagger"
	_ "github.com/repoareta/pedeve-dms-app/backend/docs" // docs is generated by Swag CLI
	"github.com/repoareta/pedeve-dms-app/backend/internal/delivery/http"
	"github.com/repoareta/pedeve-dms-app/backend/internal/infrastructure/audit"
	"github.com/repoareta/pedeve-dms-app/backend/internal/infrastructure/config"
	"github.com/repoareta/pedeve-dms-app/backend/internal/infrastructure/database"
	"github.com/repoareta/pedeve-dms-app/backend/internal/infrastructure/encryption"
	"github.com/repoareta/pedeve-dms-app/backend/internal/infrastructure/logger"
	"github.com/repoareta/pedeve-dms-app/backend/internal/infrastructure/seed"
	"github.com/repoareta/pedeve-dms-app/backend/internal/middleware"
	"github.com/repoareta/pedeve-dms-app/backend/internal/usecase"
	"go.uber.org/zap"
)

// @title           Pedeve App Backend API
// @version         1.0
// @description     Pedeve App Backend API dengan struktur Clean Architecture
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api/v1

// @securityDefinitions.apikey  BearerAuth
// @in                          header
// @name                        Authorization
// @description                 Type "Bearer" followed by a space and JWT token. Atau menggunakan httpOnly cookie (auth_token) untuk keamanan yang lebih baik.

// @note                        Catatan Teknis API:
// @note                        1. Framework: Menggunakan Fiber v2 dengan performa tinggi (fasthttp)
// @note                        2. Architecture: Clean Architecture dengan struktur cmd/, internal/
// @note                        3. Authentication: JWT token dengan httpOnly cookie untuk mencegah XSS attacks
// @note                        4. Rate Limiting: General API (100 req/s, burst: 50), Auth endpoints (5 req/min, burst: 5)
// @note                        5. Security Headers: X-Content-Type-Options, X-XSS-Protection, CSP, HSTS
// @note                        6. CSRF Protection: Double-submit cookie pattern untuk state-changing requests
// @note                        7. Audit Logging: Semua aksi user dan error teknis dicatat dalam audit log
// @note                        8. 2FA Support: TOTP-based 2FA dengan backup codes untuk recovery
// @note                        9. Error Handling: Centralized error logging dengan stack trace untuk debugging
// @note                        10. Database: PostgreSQL/SQLite dengan GORM ORM, auto-migration enabled
// @note                        11. CORS: Configured untuk localhost:5173 (Vite dev) dan localhost:3000
func main() {
	// Inisialisasi zap logger
	logger.InitLogger()
	defer logger.Sync()
	zapLog := logger.GetLogger()

	// Inisialisasi database
	database.InitDB()

	// Load configuration (from Vault or environment)
	if _, err := config.LoadConfig(); err != nil {
		zapLog.Warn("Failed to load config, using defaults", zap.Error(err))
	}

	// Inisialisasi encryption
	if err := encryption.InitEncryption(); err != nil {
		zapLog.Fatal("Failed to initialize encryption", zap.Error(err))
	}

	// Inisialisasi rate limiters dari config
	middleware.InitRateLimiters()

	// Inisialisasi audit logger
	audit.InitAuditLogger()

	// Mulai cleanup token CSRF
	middleware.StartCSRFTokenCleanup()

	// Mulai cleanup audit logs (retention policy)
	usecase.StartAuditLogCleanup()

	// Mulai cleanup notifikasi lama (retention policy: 90 hari default)
	usecase.StartNotificationCleanup()

	// Seed roles, superadmin, and default administrator user
	seed.SeedAll()

	// Setup Fiber app
	app := fiber.New(fiber.Config{
		BodyLimit: 10 * 1024 * 1024, // 10MB untuk upload dokumen
		ErrorHandler: func(c *fiber.Ctx, err error) error {
			// Custom error handler untuk logging error ke audit log
			code := fiber.StatusInternalServerError
			if e, ok := err.(*fiber.Error); ok {
				code = e.Code
			}

			// Log error ke audit log
			details := map[string]interface{}{
				"status_code": code,
				"error":       err.Error(),
			}
			middleware.LogTechnicalError(err, c, details)

			return c.Status(code).JSON(fiber.Map{
				"error":   "internal_error",
				"message": err.Error(),
			})
		},
	})

	// Middleware global
	app.Use(middleware.RecoverMiddleware)           // Custom recover middleware dengan error logging (harus di awal)
	app.Use(middleware.ZapLoggerMiddleware(zapLog)) // Zap logger middleware untuk HTTP requests
	app.Use(requestid.New())                        // Request ID middleware
	app.Use(middleware.SecurityHeadersMiddleware)   // Header keamanan
	app.Use(middleware.ErrorHandlerMiddleware)      // Log error teknis ke audit log

	// Rate limiting: hanya aktif di production
	// Di development (ENV != "production"), rate limiting otomatis di-bypass di middleware (lihat rate_limit.go)
	// Atau bisa disable sepenuhnya dengan DISABLE_RATE_LIMIT=true
	env := os.Getenv("ENV")
	disableRateLimit := os.Getenv("DISABLE_RATE_LIMIT") == "true"

	if disableRateLimit {
		zapLog.Info("Rate limiting completely disabled (DISABLE_RATE_LIMIT=true)")
	} else if env != "production" {
		zapLog.Info("Rate limiting will be bypassed in development mode",
			zap.String("env", env),
		)
		// Tetap tambahkan middleware, tapi akan di-bypass di dalamnya
		app.Use(middleware.RateLimitMiddleware(middleware.GeneralRateLimiter))
	} else {
		// Production: aktifkan rate limiting
		app.Use(middleware.RateLimitMiddleware(middleware.GeneralRateLimiter))
	}

	// CORS dengan peningkatan keamanan
	// Get CORS origin from environment variable, fallback to localhost for development
	corsOrigin := os.Getenv("CORS_ORIGIN")
	if corsOrigin == "" {
		corsOrigin = "http://localhost:5173,http://localhost:3000"
		zapLog.Info("CORS origin not set, using default localhost origins")
	} else {
		zapLog.Info("CORS origin configured", zap.String("origin", corsOrigin))
	}

	// Split comma-separated origins into slice for Fiber CORS
	// Fiber CORS AllowOrigins accepts comma-separated string or slice of strings
	// Using comma-separated string is supported and will be parsed correctly
	app.Use(cors.New(cors.Config{
		AllowOrigins:     corsOrigin, // Comma-separated string is supported by Fiber CORS
		AllowMethods:     "GET,POST,PUT,DELETE,OPTIONS,PATCH",
		AllowHeaders:     "Accept,Authorization,Content-Type,X-CSRF-Token,X-Requested-With",
		ExposeHeaders:    "Link,X-Total-Count",
		AllowCredentials: true,
		MaxAge:           300,
	}))

	// Static file server untuk uploads
	app.Static("/uploads", "./uploads")

	// Routes
	app.Get("/", indexHandler)
	app.Get("/health", healthHandler)

	// API v1
	api := app.Group("/api/v1")
	api.Get("/", apiInfoHandler)

	// Endpoint token CSRF (public, tidak perlu auth)
	api.Get("/csrf-token", http.GetCSRFTokenHandler)

	// Route autentikasi (public) - dengan rate limiting (bypass di development)
	// AuthRateLimitMiddleware akan otomatis bypass di development (lihat rate_limit.go)
	authPublic := api.Group("/auth", middleware.AuthRateLimitMiddleware)
	authPublic.Post("/login", http.Login)

	// Route yang dilindungi (memerlukan JWT)
	protected := api.Group("", middleware.JWTAuthMiddleware, middleware.CSRFMiddleware)

	// Endpoint profil dan logout user
	protected.Get("/auth/profile", http.GetProfile)
	protected.Put("/auth/profile/email", http.UpdateProfileEmail)
	protected.Put("/auth/profile/password", http.ChangePassword)
	protected.Post("/auth/logout", http.Logout)

	// Route 2FA (Two-Factor Authentication)
	protected.Post("/auth/2fa/generate", http.Generate2FASecret)
	protected.Post("/auth/2fa/verify", http.Verify2FA)
	protected.Post("/auth/2fa/disable", http.Disable2FA)
	protected.Get("/auth/2fa/status", http.Get2FAStatus)

	// Route audit logs
	protected.Get("/audit-logs", http.GetAuditLogsHandler)
	protected.Get("/audit-logs/stats", http.GetAuditLogStatsHandler)
	protected.Get("/user-activity-logs", http.GetUserActivityLogsHandler) // Permanent logs untuk data penting

	// Route documents (dilindungi)
	// Catatan: Route yang lebih spesifik harus didefinisikan sebelum route dengan parameter
	documentHandler := http.NewDocumentHandler(usecase.NewDocumentUseCase())
	protected.Get("/documents/folders", documentHandler.ListFolders)
	protected.Post("/documents/folders", documentHandler.CreateFolder)
	protected.Put("/documents/folders/:id", documentHandler.UpdateFolder)
	protected.Delete("/documents/folders/:id", documentHandler.DeleteFolder)
	protected.Post("/documents/upload", documentHandler.UploadDocument)
	protected.Get("/documents", documentHandler.ListDocuments)
	protected.Get("/documents/summary", documentHandler.DocumentSummary) // ringkasan storage, pastikan sebelum :id
	protected.Get("/documents/:id", documentHandler.GetDocument)
	protected.Put("/documents/:id", documentHandler.UpdateDocument)
	protected.Delete("/documents/:id", documentHandler.DeleteDocument)

	// Route document types (dilindungi)
	documentTypeHandler := http.NewDocumentTypeHandler(usecase.NewDocumentTypeUseCase())
	protected.Get("/document-types", documentTypeHandler.GetAllDocumentTypes)
	protected.Post("/document-types", documentTypeHandler.CreateDocumentType)
	protected.Put("/document-types/:id", documentTypeHandler.UpdateDocumentType)
	protected.Delete("/document-types/:id", documentTypeHandler.DeleteDocumentType)

	// Shareholder Types routes
	shareholderTypeHandler := http.NewShareholderTypeHandler(usecase.NewShareholderTypeUseCase())
	protected.Get("/shareholder-types", shareholderTypeHandler.GetAllShareholderTypes)
	protected.Post("/shareholder-types", shareholderTypeHandler.CreateShareholderType)
	protected.Put("/shareholder-types/:id", shareholderTypeHandler.UpdateShareholderType)
	protected.Delete("/shareholder-types/:id", shareholderTypeHandler.DeleteShareholderType)

	// Director Positions routes
	directorPositionHandler := http.NewDirectorPositionHandler(usecase.NewDirectorPositionUseCase())
	protected.Get("/director-positions", directorPositionHandler.GetAllDirectorPositions)
	protected.Post("/director-positions", directorPositionHandler.CreateDirectorPosition)
	protected.Put("/director-positions/:id", directorPositionHandler.UpdateDirectorPosition)
	protected.Delete("/director-positions/:id", directorPositionHandler.DeleteDirectorPosition)

	// Route Notifications (dilindungi)
	notificationHandler := http.NewNotificationHandler(usecase.NewNotificationUseCase())
	protected.Get("/notifications", notificationHandler.GetNotifications)
	protected.Get("/notifications/inbox", notificationHandler.GetNotificationsWithFilters)
	protected.Get("/notifications/stream", notificationHandler.StreamNotifications)
	protected.Get("/notifications/unread-count", notificationHandler.GetUnreadCount)
	protected.Put("/notifications/:id/read", notificationHandler.MarkAsRead)
	protected.Put("/notifications/read-all", notificationHandler.MarkAllAsRead)
	protected.Delete("/notifications/delete-all", notificationHandler.DeleteAllNotifications)

	// Route Upload (dilindungi)
	protected.Post("/upload/logo", http.UploadLogo)

	// Route File Serving (DILINDUNGI - memerlukan authentication)
	// Format: /api/v1/files/logos/filename.png atau /api/v1/files/documents/filename.pdf
	// Catatan: File documents bersifat rahasia, harus dilindungi dengan authentication
	// Frontend harus mengirim cookie (credentials) untuk mengakses file
	protected.Get("/files/*", http.ServeFile)

	// Route Company Management (dilindungi)
	companyHandler := http.NewCompanyHandler(usecase.NewCompanyUseCase())
	protected.Post("/companies", companyHandler.CreateCompany)
	protected.Post("/companies/full", companyHandler.CreateCompanyFull)
	protected.Get("/companies", companyHandler.GetAllCompanies)
	protected.Get("/companies/:id/users", companyHandler.GetCompanyUsers)
	protected.Get("/companies/:id/ancestors", companyHandler.GetCompanyAncestors)
	protected.Get("/companies/:id/children", companyHandler.GetCompanyChildren)
	protected.Get("/companies/:id", companyHandler.GetCompany)
	protected.Put("/companies/:id", companyHandler.UpdateCompany)
	protected.Put("/companies/:id/full", companyHandler.UpdateCompanyFull)
	protected.Delete("/companies/:id", companyHandler.DeleteCompany)

	// Route User Management (dilindungi)
	userManagementHandler := http.NewUserManagementHandler(usecase.NewUserManagementUseCase())
	protected.Post("/users", userManagementHandler.CreateUser)
	protected.Get("/users", userManagementHandler.GetAllUsers)
	// Route spesifik harus didefinisikan sebelum route dengan parameter umum
	protected.Patch("/users/:id/toggle-status", userManagementHandler.ToggleUserStatus)
	protected.Post("/users/:id/reset-password", userManagementHandler.ResetUserPassword)
	protected.Post("/users/:id/assign-company", userManagementHandler.AssignUserToCompany)
	protected.Post("/users/:id/unassign-company", userManagementHandler.UnassignUserFromCompany)
	protected.Get("/users/me/companies", userManagementHandler.GetMyCompanies) // Get all companies assigned to current user
	protected.Get("/users/:id", userManagementHandler.GetUser)
	protected.Put("/users/:id", userManagementHandler.UpdateUser)
	protected.Delete("/users/:id", userManagementHandler.DeleteUser)

	// Route Role Management (dilindungi)
	roleManagementHandler := http.NewRoleManagementHandler(usecase.NewRoleManagementUseCase())
	protected.Post("/roles", roleManagementHandler.CreateRole)
	protected.Get("/roles", roleManagementHandler.GetAllRoles)
	protected.Get("/roles/:id", roleManagementHandler.GetRole)
	protected.Put("/roles/:id", roleManagementHandler.UpdateRole)
	protected.Delete("/roles/:id", roleManagementHandler.DeleteRole)
	// Route Role Permissions (dilindungi)
	protected.Get("/roles/:id/permissions", roleManagementHandler.GetRolePermissions)
	protected.Post("/roles/:id/permissions", roleManagementHandler.AssignPermissionToRole)
	protected.Delete("/roles/:id/permissions", roleManagementHandler.RevokePermissionFromRole)

	// Route Report Management (dilindungi)
	// Catatan: Route yang lebih spesifik harus didefinisikan sebelum route dengan parameter
	reportHandler := http.NewReportHandler(usecase.NewReportUseCase())
	// Route spesifik harus didefinisikan sebelum route generic
	protected.Get("/reports/template", reportHandler.DownloadTemplate)
	protected.Post("/reports/validate", reportHandler.ValidateExcelFile)
	protected.Post("/reports/upload", reportHandler.UploadReports)
	protected.Get("/reports/export/excel", reportHandler.ExportReportsExcel)
	protected.Get("/reports/export/pdf", reportHandler.ExportReportsPDF)
	protected.Get("/reports/company/:company_id", reportHandler.GetReportsByCompany)
	// Route generic setelah route spesifik
	protected.Post("/reports", reportHandler.CreateReport)
	protected.Get("/reports", reportHandler.GetAllReports)
	protected.Get("/reports/:id", reportHandler.GetReport)
	protected.Put("/reports/:id", reportHandler.UpdateReport)
	protected.Delete("/reports/:id", reportHandler.DeleteReport)

	// Financial Report routes (RKAP & Realisasi)
	financialReportHandler := http.NewFinancialReportHandler(usecase.NewFinancialReportUseCase())
	protected.Post("/financial-reports", financialReportHandler.CreateFinancialReport)
	protected.Get("/financial-reports/company/:company_id", financialReportHandler.GetFinancialReportsByCompanyID)
	protected.Get("/financial-reports/rkap-years/:company_id", financialReportHandler.GetRKAPYearsByCompanyID)
	protected.Get("/financial-reports/compare", financialReportHandler.GetComparison)
	protected.Get("/financial-reports/:id", financialReportHandler.GetFinancialReportByID)
	protected.Put("/financial-reports/:id", financialReportHandler.UpdateFinancialReport)
	protected.Delete("/financial-reports/:id", financialReportHandler.DeleteFinancialReport)
	protected.Get("/companies/:company_id/performance/export/excel", financialReportHandler.ExportPerformanceExcel)

	// Route Permission Management (dilindungi)
	permissionManagementHandler := http.NewPermissionManagementHandler(usecase.NewPermissionManagementUseCase())
	protected.Post("/permissions", permissionManagementHandler.CreatePermission)
	protected.Get("/permissions", permissionManagementHandler.GetAllPermissions)
	protected.Get("/permissions/:id", permissionManagementHandler.GetPermission)
	protected.Put("/permissions/:id", permissionManagementHandler.UpdatePermission)
	protected.Delete("/permissions/:id", permissionManagementHandler.DeletePermission)

	// Route Development (hanya superadmin)
	developmentHandler := http.NewDevelopmentHandler(usecase.NewDevelopmentUseCase())
	// Individual endpoints (kept for backward compatibility)
	protected.Post("/development/reset-subsidiary", developmentHandler.ResetSubsidiaryData)
	protected.Post("/development/run-subsidiary-seeder", developmentHandler.RunSubsidiarySeeder)
	protected.Get("/development/check-seeder-status", developmentHandler.CheckSeederDataExists)
	protected.Post("/development/reset-reports", developmentHandler.ResetReportData)
	protected.Post("/development/run-report-seeder", developmentHandler.RunReportSeeder)
	protected.Get("/development/check-report-status", developmentHandler.CheckReportDataExists)
	// Combined endpoints (recommended)
	protected.Post("/development/run-all-seeders", developmentHandler.RunAllSeeders)
	protected.Post("/development/reset-all-seeded-data", developmentHandler.ResetAllSeededData)
	protected.Get("/development/check-all-seeder-status", developmentHandler.CheckAllSeederStatus)
	protected.Post("/development/create-test-notification", developmentHandler.CreateTestNotification)
	protected.Post("/development/create-test-notifications", developmentHandler.CreateTestNotifications)
	protected.Post("/development/check-expiring-documents", developmentHandler.CheckExpiringDocuments)
	protected.Post("/development/create-notification-for-document", developmentHandler.CreateNotificationForDocument)

	// Route SonarQube (hanya superadmin/admin)
	// Feature flag: ENABLE_SONARQUBE_MONITOR (default: true untuk local, false untuk production/development server)
	enableSonarQubeMonitor := os.Getenv("ENABLE_SONARQUBE_MONITOR")
	// Default: enable di local development (ENV != "production"), disable di production/development server
	// Set ENABLE_SONARQUBE_MONITOR=true untuk force enable, false untuk force disable
	shouldEnableSonarQube := true
	if enableSonarQubeMonitor != "" {
		shouldEnableSonarQube = enableSonarQubeMonitor == "true"
	} else if env == "production" {
		// Default: disable di production (bisa di-override dengan env var)
		shouldEnableSonarQube = false
	}

	// SonarQube handler (dibuat terlepas dari enable/disable untuk status endpoint)
	sonarqubeHandler := http.NewSonarQubeHandler()

	// Status endpoint (public untuk frontend check, tidak perlu auth)
	api.Get("/sonarqube/status", sonarqubeHandler.GetStatus)

	if shouldEnableSonarQube {
		protected.Get("/sonarqube/issues", sonarqubeHandler.GetIssues)
		protected.Get("/sonarqube/issues/export", sonarqubeHandler.ExportIssues)
		protected.Get("/sonarqube/quality", sonarqubeHandler.GetSoftwareQualityMetrics)
		zapLog.Info("SonarQube Monitor enabled",
			zap.String("env", env),
			zap.String("enable_flag", enableSonarQubeMonitor),
		)
	} else {
		zapLog.Info("SonarQube Monitor disabled",
			zap.String("env", env),
			zap.String("enable_flag", enableSonarQubeMonitor),
			zap.String("reason", "ENABLE_SONARQUBE_MONITOR not set to 'true' or running in production"),
		)
	}

	// Swagger documentation dengan auto-reload
	app.Get("/swagger/*", swagger.HandlerDefault)

	// Swagger regeneration endpoint (untuk development)
	protected.Post("/swagger/regenerate", http.RegenerateSwagger)

	// Swagger JSON/YAML dengan no-cache headers untuk auto-reload
	app.Get("/swagger.json", http.GetSwaggerJSON)
	app.Get("/swagger.yaml", http.GetSwaggerYAML)

	// Start server
	// Listen on 0.0.0.0 to accept connections from all interfaces (not just localhost)
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	listenAddr := "0.0.0.0:" + port
	zapLog.Info("Server starting",
		zap.String("listen_addr", listenAddr),
		zap.String("port", port),
		zap.String("swagger", "http://localhost:"+port+"/swagger/index.html"),
	)
	if err := app.Listen(listenAddr); err != nil {
		zapLog.Fatal("Failed to start server", zap.Error(err))
	}
}

// indexHandler returns basic API information
func indexHandler(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{
		"message": "Pedeve App Backend API",
		"version": "1.0.0",
		"docs":    "/swagger/index.html",
	})
}

// healthHandler returns health status
// @Summary      Health Check
// @Description  Mengecek status kesehatan API. Endpoint ini public dan tidak memerlukan authentication. Digunakan untuk monitoring dan health checks.
// @Tags         General
// @Accept       json
// @Produce      json
// @Success      200  {object}  map[string]string  "API sehat. Response berisi status: 'OK' dan service: 'pedeve-backend'"
// @Router       /health [get]
// @note         Catatan Teknis:
// @note         1. Public Endpoint: Endpoint ini tidak memerlukan authentication
// @note         2. Monitoring: Digunakan untuk health checks oleh load balancer atau monitoring tools
// @note         3. Response: Response selalu berisi status: 'OK' jika API berjalan dengan baik
func healthHandler(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{
		"status":  "OK",
		"service": "pedeve-backend",
	})
}

// apiInfoHandler returns API information
// @Summary      Informasi API
// @Description  Mengembalikan informasi tentang API termasuk versi dan daftar endpoint. Endpoint ini public dan tidak memerlukan authentication.
// @Tags         General
// @Accept       json
// @Produce      json
// @Success      200  {object}  map[string]interface{}  "Informasi API berhasil diambil. Response berisi api, version, dan endpoints"
// @Router       /api/v1 [get]
// @note         Catatan Teknis:
// @note         1. Public Endpoint: Endpoint ini tidak memerlukan authentication
// @note         2. API Version: Mengembalikan versi API saat ini
// @note         3. Endpoints: Mengembalikan daftar endpoint yang tersedia
func apiInfoHandler(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{
		"api":     "Pedeve App Backend API",
		"version": "1.0.0",
		"endpoints": fiber.Map{
			"documents": "/api/v1/documents",
			"swagger":   "/swagger/index.html",
		},
	})
}
